name: Build

on:
  pull_request:
    branches:
    - trunk
    
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - uses: ilammy/msvc-dev-cmd@v1
      with: 
        # must match build.fs
        toolset: 14.34

    - name: Setup .NET
      uses: actions/setup-dotnet@v3

    - name: Build and pack 
      run: ./build pack -configuration Release -prepareMachine /p:Platform='Any CPU'