name: Build and pack

on:
  pull_request:
    branches:
    - trunk
    
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - uses: ilammy/msvc-dev-cmd@v1
      with: 
        # must match build.fs
        toolset: 14.34

    - name: Setup .NET
      uses: actions/setup-dotnet@v3

    - name: Build and pack 
      run: ./build pack --configuration Release --platform x64-windows --platform x86-windows

    - uses: actions/upload-artifact@v3
      name: Upload package and logs
      if: always()
      with:
        name: build-log
        path: |
          ./dotnetbuild.binlog
          dist

    - name: Run tests (dotnet)
      run: ./build dotnet:test --configuration Release --results data

    - name: Report tests (dotnet)
      uses: dorny/test-reporter@v1
      if: ${{ always() }}  
      with:
        name: test
        path: data/*.trx
        reporter: dotnet-trx